<table>
    <thead>
        <tr>
            <th>first_name</th>
            <th>last_name</th>
            <th>ic</th>
            <th>email</th>
            <th>phoneno</th>
            <th>price</th>
            <th>quantity</th>
            <th>payment</th>
            <th>status</th>
            <th>pay_method</th>
            <th>offer_id</th>
        
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>John</td>
            <td>Doe</td>
            <td>912345006789</td>
            <td>example@gmail.com</td>
            <td>+60123456789</td>
            <td>199</td>
            <td>1</td>
            <td>199</td>
            <td>paid</td>
            <td>CDM/FPX/Senang Pay</td>
            <td>OFF001</td>
        </tr>
</tbody>