<table>
    <thead>
        <tr>
            <th>first_name</th>
            <th>last_name</th>
            <th>ic</th>
            <th>email</th>
            <th>phoneno</th>
            <th>ticket_type</th>
        
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>John</td>
            <td>Doe</td>
            <td>912345006789</td>
            <td>example@gmail.com</td>
            <td>+60123456789</td>
            <td>paid/free</td>
        </tr>
</tbody>